a=int(input('enter a value'))
b=int(input('enter b value'))
print('addition:',a+b)
print('subtraction: ',a-b)
print('division: ',a/b)
print('modulo: ',a%b)
print('floor division: ',a//b)
print('multiplication: ',a*b)
print('power: ',a**b)