s1name = input('Enter student name1') 
s1age = int(input('Enter student1 age')) 
s1address = input('Enter student1 address') 
s1college = input('Enter student1 college') 
Student1 = (s1name,s1age,s1address,s1college) 
print('Student details',Student1) 
s2name = input('Enter student name1') 
s2age = int(input('Enter student1 age')) 
s2address = input('Enter student1 address') 
s2college = input('Enter student1 college') 
Student2 = (s2name,s2age,s2address,s2college) 
print('Student details',Student2) 
print('Details of student after concatenation') 
print(Student1+Student2)